# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: MSBuild@1
  inputs:
    solution: '**/db.sqlproj'
    configuration: '$(buildConfiguration)'
    clean: true
    msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/microwiki.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishPipelineArtifact@0
  displayName: Push Artifact
  inputs:
    artifactName: 'microwiki-publish-output'
    targetPath: '$(Build.ArtifactStagingDirectory)'
