# Build Pipeline

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: MSBuild@1
  displayName: 'Database Build'
  inputs:
    solution: '**/db.sqlproj'
    configuration: '$(buildConfiguration)'
    clean: true
    msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

- task: Npm@1
  displayName: 'NPM Package Restore'
  inputs:
    command: 'ci'
    workingDir: '$(Build.SourcesDirectory)/microwiki'

- task: Npm@1
  displayName: 'NPM Build'
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)/microwiki'
    customCommand: 'run build'

- task: Npm@1
  displayName: 'NPM Build CSS'
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)/microwiki'
    customCommand: 'run build-css'

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '3.1.301'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: Push Artifact
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'microwiki-publish-output'
    publishLocation: 'Container'
