name: Deploy

on:
  push:
    # tags: [ "release-*" ]
    tags: [ "release-test-*" ]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    environment: production
    env:
      DOTNET_PROJECT_FOLDER: ${{ github.workspace }}/microwiki
      DATABASE_RELEASE_FOLDER: ${{ github.workspace }}/db/releases
      PUBLISH_OUTPUT_FOLDER: ${{ github.workspace }}/publish-output
    defaults:
      run:
        working-directory: ${{ env.DOTNET_PROJECT_FOLDER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Restore NuGet dependencies
        run: dotnet restore

      - name: Restore NPM dependencies
        run: npm ci

      - name: Build UI
        run: ./build-front-end.sh

      - name: Publish application
        run: dotnet publish --configuration Release --output ${{ env.PUBLISH_OUTPUT_FOLDER }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.3
        with:
            name: microwiki-app
            path: ${{ env.PUBLISH_OUTPUT_FOLDER }}

      - name: Upload database release artifact
        uses: actions/upload-artifact@v3.1.3
        with:
            name: microwiki-db
            path: ${{ env.DATABASE_RELEASE_FOLDER }}

  deploy:
    name: Deploy
    needs: build
    runs-on: [self-hosted, web-vm]
    environment: production
    steps:
      - name: Clean work folder
        run: rm -rf ${{ github.workspace }}/*

      - name: Download artifacts
        uses: actions/download-artifact@v3.0.2

      #- name: Apply database release scripts
      #  run: ~/dbup-cli/dbup ${{ github.workspace }}/microwiki-db "${{ secrets.CONNECTION_STRING_DEPLOY }}"

      #- name: Copy files
      #  run: sudo cp -a ${{ github.workspace }}/microwiki-app/* /var/www/microwiki

      #- name: Restart service
      #  run: sudo systemctl restart microwiki.service
